// Innitial Load:
/*
    1. Ensuring Canvas Size:
        i. Declare the canvas constant.
        ii. Declare sizing variables.
        iii. Function that will assaign sizing.
            a. Will be called on initial load.
            b. Will be recalled when window is resized.
    2. gridSize Variable: Declares the gap sized of the grid.
    3. gridArray: A matrix.
        - Generated by the viewPort Size and the gidSize Variable.
        = Maybe Tweeked to be villed with ClassObjects.
    4. populateGrid():
        - generates the base grid, with all empty cell currently represented as small cicles.
        -

    -- Setting Up animation loop in advance, giving my self a space I can experiment with.
*/

import Cell from "./cells.js";

const canvas = document.getElementById("gameCanvas");
let ctx = canvas.getContext("2d");

let viewWidth = window.innerWidth * 0.9;
let viewHeight = window.innerHeight;
let gridSize = 64;
let gridArray = Array.from(
  Array(Math.floor(viewHeight / gridSize)),
  () => new Array(Math.floor(viewWidth / gridSize))
);
let gridWidth = gridArray[0].length;
let gridHeight = gridArray.length;
let active = [];
let running = false;
let speed = 0;

function populateGrid(matrix) {
  for (let y = 0; y < matrix.length; y++) {
    for (let x = 0; x < matrix[y].length; x++) {
      let newCell = new Cell(x, y);
      matrix[y][x] = newCell;
      matrix[y][x].renderCell(ctx, gridSize);
    }
  }
}
function determinStatus(matrix) {
  for (let y = 0; y < matrix.length; y++) {
    for (let x = 0; x < matrix[y].length; x++) {
      matrix[y][x].renderCell(ctx, gridSize);
      if (running === true) {
        matrix[y][x].findNeighbors(matrix);
      }
    }
  }
}

function updateMatrix(matrix) {
  for (let y = 0; y < matrix.length; y++) {
    for (let x = 0; x < matrix[y].length; x++) {
      matrix[y][x].renderCell(ctx, gridSize);
      if (running === true) {
        matrix[y][x].updateGeneration();
      }
    }
  }
}

function setBoard() {
  viewWidth = window.innerWidth * 0.90;
  viewHeight = window.innerHeight;
  canvas.height = viewHeight;
  canvas.width = viewWidth;
  viewWidth = window.innerWidth;
  viewHeight = window.innerHeight;
  gridArray = Array.from(
    Array(viewHeight % gridSize),
    () => new Array(viewWidth % gridSize)
  );
  populateGrid(gridArray);
  active = gridArray;
}

console.log(gridHeight, gridWidth);

setBoard();
window.addEventListener("resize", setBoard);

function clickHandler(e) {
  let x = Math.round((e.layerX - gridSize / 2) / gridSize);
  let y = Math.round((e.layerY - gridSize / 2) / gridSize);
  if (active[y][x].live === false) {
    active[y][x].setLive();
  } else {
    active[y][x].setDead();
  }
}

canvas.addEventListener("click", (e) => clickHandler(e));
const startButton = document.getElementById("start");
const pauseButton = document.getElementById("pause");

startButton.addEventListener("click", () => {
  running = true;
});
pauseButton.addEventListener("click", () => {
  running = false;
  speed = 0;
  console.log(active);
});

function runtimeHandler() {
  if (running === true) {
    speed = 5000;
    console.log("Sim Running");
  }
}

let frame = 0;
let framLimit = 10;

function draw() {
  ctx.clearRect(0, 0, viewWidth, viewHeight);
  determinStatus(active);
  updateMatrix(active);
  runtimeHandler();
}

function animate() {
  frame++;
  if (frame % framLimit === 0) {
    frame = 0;
    draw();
  }
  requestAnimationFrame(animate);
}

animate();
